FROM %IMAGE%
MAINTAINER Hendrik 'T4cC0re' Meyer <mail@t4cc0.re>%APACHE1%

# deleted after build:
ARG buildDeps=""

# kept after build:
ARG packages="git libmcrypt-dev zlib1g-dev libgeoip-dev libmemcached-dev"

# PHP extensions to build and register:
ARG extensions="sockets mcrypt mbstring zip pdo pdo_mysql"

# from https://github.com/Zakay/geoip
ARG GEOIP_VERSION="master"

# Xdebug stuff
ARG XDEBUG_VERSION="2.4.0"
ARG XDEBUG_SHA1="a9bc9c6b9e8bc913fb1f7c6f6d19f6222d430414"

# Xdebug stuff
ARG MEMCACHED_BUILD_VERSION="5e42fa985b05cb1063a74a74ac14220d52652686"

RUN set -x\
  && apt-get update\
  && apt-get install -y $buildDeps $packages\
  && (\
    pecl install memcached\
    || (\
      echo "PHP7, not using PECL"\
      &&  curl -SL "https://github.com/php-memcached-dev/php-memcached/archive/$MEMCACHED_BUILD_VERSION.tar.gz" -o memcached.tgz\
        && mkdir -p /usr/src/memcached\
        && tar -xf memcached.tgz -C /usr/src/memcached --strip-components=1\
        && rm memcached.*\
        && cd /usr/src/memcached\
        && phpize\
        && ./configure\
        && make -j"$(nproc)"\
        && make install\
        && make clean\
      )\
    )\
  && docker-php-ext-install $extensions\
  && curl -SL "http://www.xdebug.org/files/xdebug-$XDEBUG_VERSION.tgz" -o xdebug.tgz\
    && echo $XDEBUG_SHA1 xdebug.tgz | sha1sum -c -\
    && mkdir -p /usr/src/xdebug\
    && tar -xf xdebug.tgz -C /usr/src/xdebug --strip-components=1\
    && rm xdebug.*\
    && cd /usr/src/xdebug\
    && phpize\
    && ./configure\
    && make -j"$(nproc)"\
    && make install\
    && make clean\
  && curl -SL "https://github.com/Zakay/geoip/archive/$GEOIP_VERSION.tar.gz" -o geoip.tgz\
    && mkdir -p /usr/src/geoip\
    && tar -xf geoip.tgz -C /usr/src/geoip --strip-components=1\
    && rm geoip.*\
    && cd /usr/src/geoip\
    && phpize\
    && ./configure\
    && make -j"$(nproc)"\
    && make install\
  && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"\
    && php composer-setup.php -- --install-dir=/bin --filename composer\
    && rm -rf composer-setup.php\
  && echo 'date.timezone = "UTC"' >> /usr/local/etc/php/php.ini\%APACHE2%
  && apt-get purge -y --auto-remove $buildDeps\
    && rm -rf /var/lib/apt/lists/*
RUN echo "zend_extension=$(find / -name xdebug.so | head -1)" > /usr/local/etc/php/conf.d/ext-xdebug.ini\
  && echo "extension=$(find / -name geoip.so | head -1)" > /usr/local/etc/php/conf.d/ext-geoip.ini\
  && echo "extension=$(find / -name memcached.so | head -1)" > /usr/local/etc/php/conf.d/ext-memcached.ini\%APACHE3%
